import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./storeProvider";
import Navigation from "@/components/ui/navigation/navigation";

export const metadata: Metadata = {
  title: "Blog WebSite",
  description: "Generated by garseta yusuf",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="id">
      <body>
        <Providers>
          <Navigation />
          {children}
        </Providers>
      </body>
    </html>
  );
}
